config/routes.rb
Rails.application.routes.draw do
	resources :characters

  get 'welcome/index'

  get 'characters/index'

  get 'items/index'

   root 'welcome#index'

   get 'characters/:id(.:format)' => 'character#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ActiveRecord::Base
	validates :name, presence: true,
                    length: { minimum: 3 }
	validates :age, presence: true,
                    length: { minimum: 1 },
		    length: { maximum: 3 }
	validates :description, presence: true,
                    length: { minimum: 10 }		    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   http_basic_authenticate_with name: "test", password: "test", except: [:index, :show]
  
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
	@characters = Character.all
  end
  
  def new
	@character = Character.new
  end
  
  def create
	  @character = Character.new(character_params)

	  	if @character.save
		redirect_to @character
		else
		render 'new'
		end
  end
  
  def show
	@character = Character.find(params[:id])
  end
  
  def update
	@character = Character.find(params[:id])

	if @character.update(character_params)
	redirect_to @character
	else
	render 'edit'
	end
  end
  
  def edit
	@character = Character.find(params[:id])
  end
  
  def destroy
	@character = Character.find(params[:id])
	@character.destroy

	redirect_to controller:'characters'
  end
  
  private
  def character_params
    params.require(:character).permit(:name, :age, :description)
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/characters/_character_basic_form.html.erb
<%= form_for @character do |f| %>

  <% if @character.errors.any? #if there were any errors %>
  <div id="error_explanation">
    <h2><%= pluralize(@character.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @character.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>



  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :age %><br>
    <%= f.text_area :age %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/characters/edit.html.erb
<div class="container">
	<div class="center_div">

<h1>Edit character</h1>

<%= render 'character_basic_form' %>

	</div>
</div>

app/views/characters/index.html.erb
<div class="container">
	<div class="center_div">

<p>Bellow is a list of all characters created so far.</p>

<table border=1>
<th>Name</th>
<th>*</th>
<th>/</th>
<th>X</th>
<th>Age</th>
<th>Description</th>

<% @characters.each do |character| %>
<tr>
  <td><%= character.name %></td>
  <td><%= link_to 'Show', character %></td>
  <td><%= link_to 'Edit', edit_character_path(character) %></td>
      <td><%= link_to 'Destroy', character_path(character),
                    method: :delete, data: { confirm: 'Delete?' } %></td>
  <td><%= character.age %></td>
  <td><%= character.description %></td>
</tr>
<% end %>
</table>

	</div>
</div>

app/views/characters/new.html.erb
<div class="container">
	<div class="center_div">

<h1>New character</h1>

<%= render 'character_basic_form' %>


	</div>
</div>

app/views/characters/show.html.erb
<div class="container">
	<div class="center_div">

<table>
<th>Name</th>
<th>Age</th>
<th>Description</th>
<tr>
  <td><%= @character.name %></td>
  <td><%= @character.age %></td>
  <td><%= @character.description %></td>
</tr>
</table>

	</div>
</div>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Octopus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "welcome/header" %>
<%= render "welcome/menu" %>

<%= yield %>

<%= render "welcome/footer" %>

</body>
</html>

app/views/welcome/_footer.html.erb
<div id="footer-box">
	<p id="footer" class="clearfix">
	Octopus team 2016
	</p>
</div>

app/views/welcome/_header.html.erb
<div id="header-box">
	<div id="header">
	<%= link_to "Octopus >> GURPS Character Sheet", "/" %>
	<br/>
	For destructive actions you'll be asked for login:password, put 'test' for both.
	</div>
</div>

app/views/welcome/_login_form.html.erb
login form: (inactive)

<% #TODO: create stuff for logins %>

app/views/welcome/_menu.html.erb
<div id="menu-box">
<ul id="menu" class="clearfix">
  <li class="first"><%= link_to 'Home', "/" %></li>
  <li><%= link_to 'New Character', new_character_path %></li>
  <li><%= link_to 'All Characters', controller:'characters' %></li>
  <li><a href="#">items (nonf)</a></li>
  <li class="last"><a href="#">logout (nonf)</a></li>
</ul>
</div>

app/views/welcome/index.html.erb
<div class="container">
	<div class="center_div">
	
	
	
<br />
	<img src="http://digital-art-gallery.com/oid/5/547x550_2114_Brell_s_2d_fantasy_warrior_girl_female_woman_picture_image_digital_art.jpg">
	</div>
</div>